# Generated by Django 4.2.8 on 2025-11-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkft', '0032_auto_20231008_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cibuild',
            name='number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='kernelchange',
            name='trigger_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
